/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Thanh Kieu
 */

package controleur;

import java.awt.Color;
import java.sql.*;
import java.util.*;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
//import vue.Lafenetre;
import controleur.edtFenetre;

public class FenetreConnexion extends javax.swing.JFrame {

    
    
    /**
     * Creates new form SQL_connect
     */
    public FenetreConnexion() {
        initComponents();
        this.jLabel3.setVisible(false);
        this.jLabel3.setForeground(Color.red);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Connexion");
        setResizable(false);

        jLabel1.setText("Nom d'utilisateur");

        jLabel2.setText("Mot de passe :");

        jTextField1.setText("Admin");
        jTextField1.setToolTipText("");
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setText("Admin");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton1.setText("Connexion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ERREUR : Mauvais identifiants.");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Thanh", "Mathilde", "Nivine" }));
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jButton1)))
                        .addContainerGap(240, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        jLabel3.setVisible(true);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Retourne la valeur dans le champ de texte jTextField1
    public String getTxtField1()
    {
        return jTextField1.getText();
    }
    //Retourne la valeur dans le champ de texte jTextField2
    public String getTxtField2()
    {
        return jTextField2.getText();
    }
    

    //Se déclenche lorsqu'on clique sur le bouton Login
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
try {
//Permet de charger le driver pour communiquer avec MySQL
Class.forName("com.mysql.jdbc.Driver");

//Permet de se connecter à la base de données
Connection connexionSQL = DriverManager.getConnection("jdbc:mysql://localhost/projetjava","root","");

//Initialise une requete qui pourra être executée pour les requêtes SQL
Statement requeteSQL = connexionSQL.createStatement();

//Execute une requête SQL et enregistre les données
ResultSet resultat_SQL=requeteSQL.executeQuery("select * from utilisateurs");
        
        String identifiant_manuel = jTextField1.getText();
        String mdp_manuel = jTextField2.getText();
          
        
       
        //Tant qu'il existe des lignes dans la table SQL
      while(resultat_SQL.next())
  {
      
      //On enregistre les identifiants SQL
      String identifiant_SQL = resultat_SQL.getString(2);
      String mdp_SQL = resultat_SQL.getString(3);
      
      //Si nos entrées correspondent aux données SQL (les identifiants correspondent bien)
        if(identifiant_manuel.equals(identifiant_SQL) && mdp_manuel.equals(mdp_SQL))
      {
          System.out.println("Connexion réussie");
          
          Statement requeteSQL_Group = connexionSQL.createStatement();
          ResultSet resultat_SQL_Groupe=requeteSQL_Group.executeQuery("select Id_groupe from etudiant where Id_utilisateur ='" + resultat_SQL.getString(1) + "'");
          
          while(resultat_SQL_Groupe.next())
          {
               Statement requeteSQL_NomGroup = connexionSQL.createStatement();
               ResultSet resultat_SQL_NomGroupe=requeteSQL_NomGroup.executeQuery("select Nom_groupe from groupe where Id_groupe ='" + resultat_SQL_Groupe.getString(1) + "'");
               
               while(resultat_SQL_NomGroupe.next())
               {
                     edtFenetre FenetreEDT = new edtFenetre(identifiant_SQL, resultat_SQL.getString(1), Integer.parseInt(resultat_SQL.getString(6)), resultat_SQL_NomGroupe.getString(1), resultat_SQL_Groupe.getString(1));
                     FenetreEDT.affichageFenetre();
               }
              
          }

          //On ferme la fenêtre de conenxion
          this.dispose();
          
      }
        
        //Sinon, on affiche un message d'erreur
      else
      {
          jLabel3.setText("ERREUR : Mauvais identifiants.");
          jLabel3.setVisible(true);
          
      }
   } 
                
} catch(Exception e){ jLabel3.setText("Problème serveur : " + e.toString()); jLabel3.setVisible(true);}


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        if(jComboBox1.getSelectedItem() == "Thanh")
        {
            jTextField1.setText("Admin");
            jTextField2.setText("Admin");
        }
        
   
        if(jComboBox1.getSelectedItem() == "Mathilde")
        {
            jTextField1.setText("TD2");
            jTextField2.setText("TD2");
        }
        
        if(jComboBox1.getSelectedItem() == "Nivine")
        {
            jTextField1.setText("TD1");
            jTextField2.setText("TD1");
        }
        
        
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetreConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetreConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetreConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetreConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                //On créer une fenêtre de connexion
               FenetreConnexion maFenetre = new FenetreConnexion();
                           
               //On l'affiche
               maFenetre.setVisible(true);
               
               //On cache par défaut le message d'erreur de connexion
              
              
            }
        });
        
        
        //Suite du code
        
      
        

        //String mdp_manuel = jTextField2.text;
        
      
        
    } //Fin main

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
